ERROR [2023-08-08 14:36:34] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 3216 6308 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:36:34] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 3216 6308 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:36:37] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 3216 6308 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:36:37] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 3216 6308 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:36:41] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 3216 6308 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:36:41] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 3216 6308 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:37:11] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 3216 6308 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:37:11] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 3216 6308 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:44:03] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 15300 8196 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:44:03] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 15300 8196 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:44:13] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 15300 8196 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:44:13] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 15300 8196 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:51:35] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 20148 19872 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 14:51:35] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 20148 19872 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:00:52] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 14448 14940 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:00:52] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 14448 14940 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:00:55] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 14448 14940 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:00:55] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 14448 14940 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:01:10] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 76 authenticate 14448 14940 
 	 Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
ERROR [2023-08-08 15:01:10] D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py 77 authenticate 14448 14940 
 	 Auto create & update UserModel fail 
Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\石化智云\2023-08数据\framework_3.3.1.92\framework_py\blueapps\account\components\bk_token\backends.py", line 45, in authenticate
    user, _ = user_model.objects.get_or_create(username=username)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "D:\石化智云\2023-08数据\dj_auth_template_blueapps_dj2\venv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'service_center.account_user' doesn't exist")
